// Mock data for conversations
export const mockConversations = [
  {
    id: 1,
    user: {
      id: 1,
      name: "Patient #123",
      avatar: "🏥",
      online: true,
    },
    participants: [
      {
        id: 1,
        name: "Dr. Sara Johnson",
        role: "doctor",
        avatar: "👩‍⚕️",
        online: true,
      },
      {
        id: 2,
        name: "Amir Hossein",
        role: "patient",
        avatar: "👤",
        online: true,
      },
      {
        id: 3,
        name: "Admin Mike",
        role: "admin",
        avatar: "👨‍💼",
        online: true,
      },
    ],
    lastMessage: {
      content: "Guys, you can find me 30 photos like the one above👆",
      timestamp: "12:32 PM",
      type: "text",
      isOwn: false,
      senderName: "Amir Hossein",
      senderRole: "patient",
    },
    unreadCount: 3,
    timestamp: "12:32 PM",
  },
  {
    id: 2,
    user: {
      id: 2,
      name: "Patient #124",
      avatar: "🏥",
      online: true,
    },
    participants: [
      {
        id: 4,
        name: "Dr. Ahmad Rahman",
        role: "doctor",
        avatar: "👨‍⚕️",
        online: true,
      },
      {
        id: 5,
        name: "Mohammad",
        role: "patient",
        avatar: "🤴",
        online: true,
      },
      {
        id: 6,
        name: "Admin Lisa",
        role: "admin",
        avatar: "👩‍💼",
        online: false,
      },
    ],
    lastMessage: {
      content: "Photo",
      timestamp: "11:45 AM",
      type: "image",
      isOwn: true,
      senderName: "Dr. Ahmad Rahman",
      senderRole: "doctor",
    },
    unreadCount: 0,
    timestamp: "11:45 AM",
  },
  {
    id: 3,
    user: {
      id: 3,
      name: "Patient #125",
      avatar: "🏥",
      online: true,
    },
    participants: [
      {
        id: 7,
        name: "Dr. Emily Chen",
        role: "doctor",
        avatar: "👩‍⚕️",
        online: true,
      },
      {
        id: 8,
        name: "Kianoosh",
        role: "patient",
        avatar: "😊",
        online: true,
      },
      {
        id: 9,
        name: "Admin John",
        role: "admin",
        avatar: "👨‍💼",
        online: true,
      },
    ],
    lastMessage: {
      content: "Voice message",
      timestamp: "10:30 AM",
      type: "voice",
      isOwn: false,
      senderName: "Kianoosh",
      senderRole: "patient",
    },
    unreadCount: 1,
    timestamp: "10:30 AM",
  },
  {
    id: 4,
    user: {
      id: 4,
      name: "Patient #126",
      avatar: "🏥",
      online: false,
    },
    participants: [
      {
        id: 10,
        name: "Dr. David Wilson",
        role: "doctor",
        avatar: "👨‍⚕️",
        online: false,
      },
      {
        id: 11,
        name: "Maral Mohseni",
        role: "patient",
        avatar: "👩",
        online: false,
      },
      {
        id: 12,
        name: "Admin Kate",
        role: "admin",
        avatar: "👩‍💼",
        online: true,
      },
    ],
    lastMessage: {
      content: "Thanks for the help!",
      timestamp: "Yesterday",
      type: "text",
      isOwn: false,
      senderName: "Maral Mohseni",
      senderRole: "patient",
    },
    unreadCount: 0,
    timestamp: "Yesterday",
  },
  {
    id: 5,
    user: {
      id: 5,
      name: "Patient #127",
      avatar: "🏥",
      online: true,
    },
    participants: [
      {
        id: 13,
        name: "Dr. Fatima Al-Rashid",
        role: "doctor",
        avatar: "👩‍⚕️",
        online: true,
      },
      {
        id: 14,
        name: "Hasan Aghaye",
        role: "patient",
        avatar: "👨",
        online: true,
      },
      {
        id: 15,
        name: "Admin Robert",
        role: "admin",
        avatar: "👨‍💼",
        online: false,
      },
    ],
    lastMessage: {
      content: "See you tomorrow",
      timestamp: "Yesterday",
      type: "text",
      isOwn: true,
      senderName: "Dr. Fatima Al-Rashid",
      senderRole: "doctor",
    },
    unreadCount: 2,
    timestamp: "Yesterday",
  },
];

// Mock messages organized by conversation ID
export const mockMessagesData = {
  1: [
    // Patient Consultation #123
    {
      id: 1,
      content: "Hey! How are you doing?",
      timestamp: "10:30 AM",
      isOwn: false,
      status: "read",
      type: "text",
      senderName: "Amir Hossein",
      senderRole: "patient",
      senderAvatar: "👤",
    },
    {
      id: 2,
      content: "I'm doing great! Just working on some designs 🎨",
      timestamp: "10:32 AM",
      isOwn: true,
      status: "read",
      type: "text",
      senderName: "Dr. Sarah Johnson",
      senderRole: "doctor",
      senderAvatar: "👩‍⚕️",
    },
    {
      id: 3,
      content: "Guys, you can find me 30 photos like the one above👆",
      timestamp: "12:32 PM",
      isOwn: false,
      status: "read",
      type: "text",
      senderName: "Amir Hossein",
      senderRole: "patient",
      senderAvatar: "👤",
    },
    {
      id: 4,
      content: "",
      timestamp: "12:33 PM",
      isOwn: false,
      status: "read",
      type: "image",
      images: ["https://images.unsplash.com/photo-1518837695005-2083093ee35b?w=200&h=150&fit=crop"],
      senderName: "Amir Hossein",
      senderRole: "patient",
      senderAvatar: "👤",
    },
    {
      id: 5,
      content: "That looks amazing! Can you send me more details?",
      timestamp: "12:34 PM",
      isOwn: true,
      status: "delivered",
      type: "text",
      senderName: "Dr. Sarah Johnson",
      senderRole: "doctor",
      senderAvatar: "👩‍⚕️",
    },
  ],
  2: [
    // Patient Consultation #124
    {
      id: 6,
      content: "Hello doctor! I need some medical advice.",
      timestamp: "9:15 AM",
      isOwn: false,
      status: "read",
      type: "text",
      senderName: "Mohammad",
      senderRole: "patient",
      senderAvatar: "🤴",
    },
    {
      id: 7,
      content: "Of course! I'm here to help. What seems to be the issue?",
      timestamp: "9:18 AM",
      isOwn: true,
      status: "read",
      type: "text",
      senderName: "Dr. Ahmad Rahman",
      senderRole: "doctor",
      senderAvatar: "👨‍⚕️",
    },
    {
      id: 8,
      content: "I've been having headaches for the past few days",
      timestamp: "9:20 AM",
      isOwn: false,
      status: "read",
      type: "text",
      senderName: "Mohammad",
      senderRole: "patient",
      senderAvatar: "🤴",
    },
    {
      id: 9,
      content: "",
      timestamp: "11:45 AM",
      isOwn: true,
      status: "delivered",
      type: "image",
      images: ["https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=200&h=150&fit=crop"],
      senderName: "Dr. Ahmad Rahman",
      senderRole: "doctor",
      senderAvatar: "👨‍⚕️",
    },
  ],
  3: [
    // Patient Consultation #125
    {
      id: 10,
      content: "Good morning doc! 🌅",
      timestamp: "8:30 AM",
      isOwn: false,
      status: "read",
      type: "text",
      senderName: "Kianoosh",
      senderRole: "patient",
      senderAvatar: "😊",
    },
    {
      id: 11,
      content: "Good morning! How can I assist you today?",
      timestamp: "8:35 AM",
      isOwn: true,
      status: "read",
      type: "text",
      senderName: "Dr. Emily Chen",
      senderRole: "doctor",
      senderAvatar: "👩‍⚕️",
    },
    {
      id: 12,
      content: "",
      timestamp: "10:30 AM",
      isOwn: false,
      status: "read",
      type: "voice",
      duration: "1:25",
      senderName: "Kianoosh",
      senderRole: "patient",
      senderAvatar: "😊",
    },
    {
      id: 13,
      content: "Thanks for the voice message! I'll review it and get back to you.",
      timestamp: "10:32 AM",
      isOwn: true,
      status: "sent",
      type: "text",
      senderName: "Dr. Emily Chen",
      senderRole: "doctor",
      senderAvatar: "👩‍⚕️",
    },
  ],
  4: [
    // Patient Consultation #126
    {
      id: 14,
      content: "Hi doctor, I wanted to follow up on my last appointment",
      timestamp: "Yesterday 2:30 PM",
      isOwn: false,
      status: "read",
      type: "text",
      senderName: "Maral Mohseni",
      senderRole: "patient",
      senderAvatar: "👩",
    },
    {
      id: 15,
      content: "Hello! Yes, I remember. How are you feeling after taking the medication?",
      timestamp: "Yesterday 2:45 PM",
      isOwn: true,
      status: "read",
      type: "text",
      senderName: "Dr. David Wilson",
      senderRole: "doctor",
      senderAvatar: "👨‍⚕️",
    },
    {
      id: 16,
      content: "Much better! The symptoms have improved significantly 😊",
      timestamp: "Yesterday 3:00 PM",
      isOwn: false,
      status: "read",
      type: "text",
      senderName: "Maral Mohseni",
      senderRole: "patient",
      senderAvatar: "👩",
    },
    {
      id: 17,
      content: "Thanks for the help!",
      timestamp: "Yesterday 3:15 PM",
      isOwn: false,
      status: "read",
      type: "text",
      senderName: "Maral Mohseni",
      senderRole: "patient",
      senderAvatar: "👩",
    },
  ],
  5: [
    // Patient Consultation #127
    {
      id: 18,
      content: "Doctor, I have a question about my prescription",
      timestamp: "Yesterday 10:00 AM",
      isOwn: false,
      status: "read",
      type: "text",
      senderName: "Hasan Aghaye",
      senderRole: "patient",
      senderAvatar: "👨",
    },
    {
      id: 19,
      content: "Sure! What would you like to know?",
      timestamp: "Yesterday 10:15 AM",
      isOwn: true,
      status: "read",
      type: "text",
      senderName: "Dr. Fatima Al-Rashid",
      senderRole: "doctor",
      senderAvatar: "👩‍⚕️",
    },
    {
      id: 20,
      content: "Should I take it with food or on an empty stomach?",
      timestamp: "Yesterday 10:20 AM",
      isOwn: false,
      status: "read",
      type: "text",
      senderName: "Hasan Aghaye",
      senderRole: "patient",
      senderAvatar: "👨",
    },
    {
      id: 21,
      content: "It's better to take it with food to avoid stomach irritation. See you tomorrow at the clinic!",
      timestamp: "Yesterday 10:25 AM",
      isOwn: true,
      status: "read",
      type: "text",
      senderName: "Dr. Fatima Al-Rashid",
      senderRole: "doctor",
      senderAvatar: "👩‍⚕️",
    },
    {
      id: 22,
      content: "See you tomorrow",
      timestamp: "Yesterday 11:00 AM",
      isOwn: false,
      status: "read",
      type: "text",
      senderName: "Hasan Aghaye",
      senderRole: "patient",
      senderAvatar: "👨",
    },
  ],
};
